# <b><div style='rgb'>NUMPY</div></b>

In [2]:
import numpy as np

In [5]:
a=np.array([[4,8,9,1],[3,1,2,6],[11,9,6,9]])

a.shape

#### Inbuilt Functions

In [8]:
a.sum(axis=1) #sum along row

array([22, 12, 35])

In [9]:
a.sum(axis=0) #sum along axis

array([18, 18, 17, 16])

In [10]:
a.mean(axis=1)

array([5.5 , 3.  , 8.75])

In [11]:
a.mean(axis=0)

array([6.        , 6.        , 5.66666667, 5.33333333])

In [14]:
a.max(axis=0)

array([11,  9,  9,  9])

In [15]:
a.max(axis=1)

array([ 9,  6, 11])

In [16]:
a.min(axis=1)

array([1, 1, 6])

In [17]:
a.min(axis=0)

array([3, 1, 2, 1])

In [18]:
a.argmax(axis=0)

array([2, 2, 0, 2], dtype=int64)

In [19]:
a.argmax(axis=1)

array([2, 3, 0], dtype=int64)

In [20]:
a.std(axis=0)

array([3.55902608, 3.55902608, 2.86744176, 3.29983165])

In [21]:
a.std(axis=1)

array([3.20156212, 1.87082869, 1.78535711])

In [23]:
a.prod()

55427328

In [24]:
a.argsort(axis=0)

array([[1, 1, 1, 0],
       [0, 0, 2, 1],
       [2, 2, 0, 2]], dtype=int64)

In [26]:
a.reshape(4,3)

array([[ 4,  8,  9],
       [ 1,  3,  1],
       [ 2,  6, 11],
       [ 9,  6,  9]])

In [29]:
x=np.random.random((3,3))
print(x)

[[0.09090467 0.78671923 0.50144448]
 [0.56777015 0.6407228  0.21545061]
 [0.24436428 0.05353911 0.46652048]]


In [31]:
x=np.random.randint(4,15,size=(3,2)) #We create 3x2 ndarray with random integers
print(x)

[[14  7]
 [13  8]
 [ 8 12]]


In [32]:
x=np.linspace(0,25,10)  # we create a rank 1 ndarray that has 10 integers evenly spaced
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [33]:
y=np.arange(20)  # we create a rank 1 ndarray with sequential integers 0 to 19
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [35]:
y.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])